### ISSUE TITLE
AttributeError: 'MistralForCasualLM' object has no attribute 'prefill_embed'

### ISSUE THREAD

**Issue by Single430** [mos-fine/mlc_llm_Modify#1]
Hello, Your job is great, but i encountered an error while using the whl (https://huggingface.co/spaces/Mos-fine/mlc_llm_Modify/tree/main) you compiled for the `mlc_llm convert_weigh ./dist/models/MiniCPM-Llama3-V-2_5 --model-type minicpm_v --quantization q4f16_1 -o dist/MiniCPM-Llama3-V-2_5-
q4f16_1-MLC` process. Upon checking the source code for `class MistralForCasualLM(nn.Module): `, I indeed could not find this function `prefill_embed`. 

`File "/usr/local/lib/python3.10/dist-packages/mlc_llm/model/mistral/mistral_model.py", line 463, in image
    return self.llm.prefill_embed(inputs, rolling_cache_len, kv_seq_len, cache_offset)
AttributeError: 'MistralForCasualLM' object has no attribute 'prefill_embed'`

**Comment by Qrrrr** [comment]
@Single430 Hi, I try to convert weight of MiniCPM-v-2 and I encountered the same error. Do you have any idea to solve it?

**Comment by Qrrrr** [comment]
@Single430 Hi, I tried to convert weight of MiniCPM-v-2 and I encountered the same error. Do you have any idea to solve it?
